import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';

import { Relics, MATCH_R } from '../../src/systems/Relics.js';

/**
 * THE RELIC LEDGER LEARNS WHICH THIRTY, NOT HOW MANY.
 *
 * ── The defect ────────────────────────────────────────────────────────────
 * `serialize` stored ONE INTEGER PER WORLD and `_applyFound` marked the first
 * N sites in generation order as taken. Within a session those coincide, so
 * the count and the money were always right. Across a reload they do not:
 * `sites` is regenerated by a seeded shuffle plus a district deal plus a dart
 * pass, and generation order has no relationship to pickup order. Collect the
 * four relics on the wall towers, reload, and the four the generator happened
 * to emit first are gone instead.
 *
 * That was written down as a KNOWN LIMITATION and accepted, on the grounds
 * that placement has no stable ids to store. For one device the reasoning
 * held: only WHICH thirty was wrong, and that is unobservable except to a
 * player who remembers a rooftop.
 *
 * ── Why it stopped being acceptable ───────────────────────────────────────
 * A count cannot be MERGED. Device A finds relics {1,3,7}; device B finds
 * {2,4}. The union of identities is five relics. The maximum of the counts is
 * three. Two relics are destroyed and the player is never told. Every other
 * progress system in the save already stores identities; this was the only one
 * that did not, so it was the blocker for remote-save parity.
 *
 * ── Why positions ARE stable ids, despite the docstring ───────────────────
 * `_tooClose` is enforced on BOTH the authored deal and the dart pass, so no
 * two sites in a world are within `MIN_APART` (14 m) of each other in XZ. So:
 *
 *   - a quantised position collides with nothing at any cell below 14/sqrt(2)
 *   - matching by NEAREST SITE within `MATCH_R` = 6 < 14/2 is provably
 *     one-to-one: no key can lie within 6 m of two sites, and no site can be
 *     claimed by two keys
 *
 * Nearest-match rather than string equality is the load-bearing half. A raw
 * string key flips the moment a position drifts across a cell boundary; the
 * tolerance absorbs that, and a drift larger than the tolerance drops the
 * relic back to un-found, which fails in the generous direction.
 *
 * Separation is XZ-only, so `y` is deliberately NOT matched on - a deck-height
 * tweak must not break an identity.
 */

/* ---------------------------------------------------------------------- */
/* Doubles                                                                 */
/* ---------------------------------------------------------------------- */

function makeBus() {
  const handlers = new Map();
  const log = [];
  return {
    log,
    on(type, fn) {
      if (!handlers.has(type)) handlers.set(type, new Set());
      handlers.get(type).add(fn);
      return () => handlers.get(type)?.delete(fn);
    },
    emit(type, payload) {
      log.push({ type, payload });
      for (const fn of [...(handlers.get(type) ?? [])]) fn(payload);
    },
    of(type) { return log.filter((e) => e.type === type).map((e) => e.payload); },
  };
}

function makeRelics() {
  const bus = makeBus();
  const player = { position: new THREE.Vector3(0, 0, 0) };
  const economy = { credits: 0, add(n) { this.credits += n; return this.credits; } };
  const inventory = {
    stored: [], acquired: [],
    add(id, n) { this.stored.push([id, n]); return n; },
    acquire(id, n) { this.acquired.push([id, n]); return { taken: n }; },
  };
  const cosmetics = {
    owned: new Set(),
    unlock(id) { if (this.owned.has(id)) return false; this.owned.add(id); return true; },
  };
  const mounts = { powers: [], grantPower(m, p, t) { this.powers.push([m, p, t]); } };
  const relics = new Relics({
    scene: new THREE.Scene(), bus, physics: null, player, economy, inventory, cosmetics, mounts,
  });
  return { bus, player, economy, inventory, cosmetics, mounts, relics };
}

/**
 * Install sites at the given XZ positions, as `_onWorld` would leave them.
 * Spacing in every fixture below respects MIN_APART, exactly as the real
 * placement guarantees.
 */
function place(ctx, worldId, points) {
  ctx.relics._worldId = worldId;
  ctx.relics.sites.length = 0;
  for (const [x, z] of points) {
    ctx.relics.sites.push({ pos: new THREE.Vector3(x, 20, z), taken: false, phase: 0 });
  }
  ctx.relics._applyFound();
  ctx.relics._announce();
}

/** A row of `n` sites 20 m apart - comfortably outside MIN_APART. */
const row = (n) => Array.from({ length: n }, (_, i) => [i * 20, 0]);

/** Walk onto one relic and run a frame. */
function collect(ctx, i) {
  const s = ctx.relics.sites[i];
  ctx.player.position.set(s.pos.x, s.pos.y - 1.0, s.pos.z);
  ctx.relics.update(1 / 60);
}

/** Which site positions are marked taken, as a sorted list of x co-ordinates. */
const takenXs = (ctx) =>
  ctx.relics.sites.filter((s) => s.taken).map((s) => Math.round(s.pos.x)).sort((a, b) => a - b);

/* ====================================================================== */
/* The identity ledger                                                     */
/* ====================================================================== */

test('the save carries which relics, not merely how many', () => {
  const ctx = makeRelics();
  place(ctx, 'citadel', row(6));
  collect(ctx, 1);
  collect(ctx, 4);

  const snap = ctx.relics.serialize();
  assert.ok(snap.foundIds, 'serialize must emit an identity ledger');
  assert.equal(snap.foundIds.citadel.length, 2);
  assert.equal(snap.found.citadel, 2,
    'the legacy count must still be written, derived from the id list');
});

test('a reload marks the relics the player actually took, not the first N', () => {
  /* THE defect. Take sites 1 and 4, then regenerate the world with the sites in
   * a DIFFERENT order - which is what a seeded reshuffle does - and the same
   * two relics must still be the missing ones. */
  const ctx = makeRelics();
  place(ctx, 'citadel', row(6));
  collect(ctx, 1);   // x = 20
  collect(ctx, 4);   // x = 80
  const snap = ctx.relics.serialize();

  const fresh = makeRelics();
  fresh.relics.deserialize(snap);
  // Same six positions, emitted in reverse - a different generation order.
  place(fresh, 'citadel', row(6).slice().reverse());

  assert.deepEqual(takenXs(fresh), [20, 80],
    'the restore marked the first N in generation order rather than the two taken');
});

test('a position that drifted slightly keeps its identity', () => {
  const ctx = makeRelics();
  place(ctx, 'citadel', row(4));
  collect(ctx, 2);                       // x = 40
  const snap = ctx.relics.serialize();

  const fresh = makeRelics();
  fresh.relics.deserialize(snap);
  // The authored deck moved 3 m - inside MATCH_R, so it is the same relic.
  place(fresh, 'citadel', [[0, 0], [20, 0], [43, 0], [60, 0]]);

  assert.deepEqual(takenXs(fresh), [43], 'a small authoring drift lost the identity');
});

test('a position that moved further than the tolerance becomes re-findable', () => {
  /* The conservative failure, and the honest half of the tradeoff: a relic that
   * genuinely moved is a different relic, and the player collects it again. */
  const ctx = makeRelics();
  place(ctx, 'citadel', row(4));
  collect(ctx, 2);
  const snap = ctx.relics.serialize();

  const fresh = makeRelics();
  fresh.relics.deserialize(snap);
  place(fresh, 'citadel', [[0, 0], [20, 0], [40, 300], [60, 0]]);

  assert.deepEqual(takenXs(fresh), [],
    'a relic that moved far away must fall back to un-found, not claim a neighbour');
});

test('height is not part of the identity', () => {
  /* Separation is XZ-only, so y cannot disambiguate and must not be matched on:
   * a deck raised by a metre is the same relic. */
  const ctx = makeRelics();
  place(ctx, 'citadel', row(3));
  collect(ctx, 1);
  const snap = ctx.relics.serialize();

  const fresh = makeRelics();
  fresh.relics.deserialize(snap);
  fresh.relics._worldId = 'citadel';
  fresh.relics.sites.length = 0;
  for (const [x, z] of row(3)) {
    fresh.relics.sites.push({ pos: new THREE.Vector3(x, 96, z), taken: false, phase: 0 });
  }
  fresh.relics._applyFound();

  assert.deepEqual(takenXs(fresh), [20], 'a height change broke the identity');
});

test('one stored key never claims two sites', () => {
  /* MATCH_R < MIN_APART/2 is what makes the assignment one-to-one. Two sites at
   * the guaranteed minimum separation, one key between them: exactly one wins. */
  const ctx = makeRelics();
  place(ctx, 'citadel', [[0, 0], [14, 0]]);
  collect(ctx, 0);
  const snap = ctx.relics.serialize();

  const fresh = makeRelics();
  fresh.relics.deserialize(snap);
  place(fresh, 'citadel', [[0, 0], [14, 0]]);

  assert.equal(takenXs(fresh).length, 1, 'a single key claimed more than one site');
  assert.ok(MATCH_R < 14 / 2,
    'MATCH_R must stay below MIN_APART/2 or the assignment stops being one-to-one');
});

/* ====================================================================== */
/* Migration from the count-based ledger                                   */
/* ====================================================================== */

test('a save written before this drop still loads', () => {
  const ctx = makeRelics();
  ctx.relics.deserialize({ found: { citadel: 3 }, paid: [] });
  place(ctx, 'citadel', row(6));

  assert.equal(ctx.relics.found, 3, 'a legacy count must still restore its number');
});

test('a legacy save is upgraded in place, so the next write carries ids', () => {
  const ctx = makeRelics();
  ctx.relics.deserialize({ found: { citadel: 2 }, paid: [] });
  place(ctx, 'citadel', row(5));

  const snap = ctx.relics.serialize();
  assert.equal(snap.foundIds?.citadel?.length, 2,
    'the upgrade must mint ids for the sites the legacy count marked');
  assert.equal(snap.found.citadel, 2);
});

/* ====================================================================== */
/* The merge - the reason any of this exists                               */
/* ====================================================================== */

test('two devices with disjoint finds converge to the union', () => {
  /* The property a count cannot have. Under the old ledger this is max(2,2)=2
   * and two relics are destroyed. */
  const a = makeRelics();
  place(a, 'citadel', row(6));
  collect(a, 0);
  collect(a, 2);

  const b = makeRelics();
  place(b, 'citadel', row(6));
  collect(b, 3);
  collect(b, 5);

  const merged = Relics.merge(a.relics.serialize(), b.relics.serialize());

  const fresh = makeRelics();
  fresh.relics.deserialize(merged);
  place(fresh, 'citadel', row(6));

  assert.deepEqual(takenXs(fresh), [0, 40, 60, 100],
    'the merge lost a device\'s relics instead of taking the union');
  assert.equal(fresh.relics.found, 4);
});

test('the merge is commutative, so no device clock is involved', () => {
  const a = makeRelics();
  place(a, 'citadel', row(6));
  collect(a, 1);
  const b = makeRelics();
  place(b, 'citadel', row(6));
  collect(b, 4);

  const ab = Relics.merge(a.relics.serialize(), b.relics.serialize());
  const ba = Relics.merge(b.relics.serialize(), a.relics.serialize());

  const ids = (m) => [...(m.foundIds.citadel ?? [])].sort();
  assert.deepEqual(ids(ab), ids(ba), 'the order the devices synced in changed the result');
});

test('merging the same payload twice changes nothing', () => {
  const a = makeRelics();
  place(a, 'citadel', row(4));
  collect(a, 2);
  const snap = a.relics.serialize();

  const once = Relics.merge(snap, snap);
  assert.equal(once.foundIds.citadel.length, 1, 'a replayed payload double-counted');
});

test('a prize paid on either device stays paid', () => {
  const a = { found: {}, foundIds: {}, paid: ['citadel:half'] };
  const b = { found: {}, foundIds: {}, paid: ['medieval:set'] };
  const merged = Relics.merge(a, b);
  assert.deepEqual([...merged.paid].sort(), ['citadel:half', 'medieval:set']);
});

/* ====================================================================== */
/* The behaviour the merge forces                                          */
/* ====================================================================== */

test('a world completed by a merge still pays the set prize', () => {
  /* `_payMilestones` only ever ran from `_collect`, so a world that became
   * complete WITHOUT a pickup - device A holding half, device B the other half -
   * never paid. `Viewpoints` records hitting exactly this and handling it on
   * world entry. */
  const a = makeRelics();
  place(a, 'citadel', row(4));
  collect(a, 0);
  collect(a, 1);

  const b = makeRelics();
  place(b, 'citadel', row(4));
  collect(b, 2);
  collect(b, 3);

  const fresh = makeRelics();
  fresh.relics.deserialize(Relics.merge(a.relics.serialize(), b.relics.serialize()));
  fresh.relics._worldId = 'citadel';
  fresh.relics.sites.length = 0;
  for (const [x, z] of row(4)) {
    fresh.relics.sites.push({ pos: new THREE.Vector3(x, 20, z), taken: false, phase: 0 });
  }
  fresh.relics._enterWorldLedger();

  assert.equal(fresh.relics.remaining, 0, 'the union did not complete the world');
  assert.ok(fresh.cosmetics.owned.size > 0,
    'a world completed by merging two half-sets never paid the set prize');
});

test('re-entering a completed world still pays nothing twice', () => {
  const ctx = makeRelics();
  place(ctx, 'citadel', row(2));
  collect(ctx, 0);
  collect(ctx, 1);
  const creditsAfterFirst = ctx.economy.credits;
  const ownedAfterFirst = ctx.cosmetics.owned.size;

  ctx.relics._enterWorldLedger();
  ctx.relics._enterWorldLedger();

  assert.equal(ctx.economy.credits, creditsAfterFirst, 'world entry paid the set prize again');
  assert.equal(ctx.cosmetics.owned.size, ownedAfterFirst);
});
