import { WORLD_MARKETS } from './ItemDefs.js';

/**
 * THE SHOP THAT WORKS WITH THE SERVER DOWN.
 *
 * ===========================================================================
 *  THE DEFECT
 * ===========================================================================
 *
 * `Marketplace._loadCatalog` fetched `/api/marketplace/items` and, on failure,
 * set `_catalogError` and returned. There was no fallback of any kind. Driven
 * cold against a `vite`-only build - which is how this game is developed and
 * how the whole flight campaign was play-tested - pressing `B` at a vendor
 * opened **FITTING SHOP - LICENSED TRADE TERMINAL**, BUY tab, All categories,
 * and drew **NOT FOUND** in the same neutral style as an empty shop.
 *
 * So: every credit the player earns buys nothing. The kill ladder, the ore
 * ladder, the bounties and the survey prizes all pay into a currency with no
 * sink. And it takes the ship-stat upgrades down with it - `ShipMenuLogic`
 * tells the player "upgrade at the Fitting Shop" and the Fitting Shop is the
 * shop that says NOT FOUND.
 *
 * Lore already degrades to bundled defaults when its endpoint is down. The
 * shop did not degrade at all, which is the harder failure of the two to
 * notice, because an empty shop looks exactly like a shop with nothing in it.
 *
 * ===========================================================================
 *  WHY THIS IS A COPY, AND WHAT STOPS IT DRIFTING
 * ===========================================================================
 *
 * These rows are `BASE_ITEMS` from `site/lib/marketplaceCatalog.ts`, which is
 * server-side TypeScript the browser bundle cannot import. Two descriptions of
 * one catalogue is exactly the failure this project keeps writing down, so the
 * copy is not trusted to stay honest by being careful:
 *
 *   `scripts/tests/marketplace-offline.test.mjs` parses the TypeScript and
 *   asserts, row by row, that every field here matches - id, name, category,
 *   both prices, the pricing kind, the world allowlist and the whole
 *   `action_config`. A price edited on the server and not here is a red test,
 *   not a shop that quietly quotes last month's rate.
 *
 * The two GENERATED arrays in that file - `MOUNT_SKIN_ROWS` and the 60
 * `MOUNT_UPGRADE_ROWS` for the non-car mounts - are deliberately NOT copied.
 * They are a product of three tables and copying a product is how a copy rots.
 * Offline, a vendor stocks the 46 hand-authored rows, which includes every
 * yard row, every consumable and all three bag expansion rigs; the mount
 * upgrade wall is the one thing that needs the API up. `offlineCatalog` says
 * so in its return value.
 *
 * ===========================================================================
 *  PRICING
 * ===========================================================================
 *
 * The server applies `WORLD_PRICE_MULTIPLIERS` per world at seed time, and
 * that table is required to match `WORLD_MARKETS` in `ItemDefs.js` exactly -
 * the TypeScript says so in a comment over `WORLD_PRICE_MULTIPLIERS.dock`. So
 * the offline builder applies the multipliers out of `WORLD_MARKETS`, which is
 * the game's own copy, rather than carrying a third one. Same arithmetic,
 * same rounding, same `Math.max(1, ...)` floor as `buildMarketplaceSeedItems`.
 */

/** One row per hand-authored `BASE_ITEMS` entry. Order is `sort_order`. */
export const OFFLINE_BASE_ITEMS = Object.freeze([
  {
    source_key: 'pack_bullets',
    name: 'Rifle Round Pack',
    description: '60 rifle rounds in one bag slot.',
    category: 'weapons',
    game_action: 'ammo_pack_rifle',
    action_config: { effect: 'grant_ammo', ammo_item: 'bullet', amount: 60 },
    quantity: null,
    cost_buy: 150,
    cost_sell: 72,
    pricing_kind: 'ammo',
    sort_order: 10,
    worlds: null,
  },
  {
    source_key: 'pack_arrows',
    name: 'Arrow Bundle',
    description: '30 broadhead arrows in one bag slot.',
    category: 'weapons',
    game_action: 'ammo_pack_arrow',
    action_config: { effect: 'grant_ammo', ammo_item: 'arrow', amount: 30 },
    quantity: null,
    cost_buy: 130,
    cost_sell: 60,
    pricing_kind: 'ammo',
    sort_order: 20,
    worlds: null,
  },
  {
    source_key: 'pack_embers',
    name: 'Ember Core Cell',
    description: '10 fireball charges in a sealed battery pack.',
    category: 'spells',
    game_action: 'ammo_pack_ember',
    action_config: { effect: 'grant_ammo', ammo_item: 'fireball_charge', amount: 10 },
    quantity: null,
    cost_buy: 170,
    cost_sell: 60,
    pricing_kind: 'ammo',
    sort_order: 30,
    worlds: null,
  },
  {
    source_key: 'pack_medkit',
    name: 'Trauma Twin-Pack',
    description: 'Two field medkits in one bag slot.',
    category: 'health',
    game_action: 'heal_50',
    action_config: { effect: 'restore_health', amount: 50 },
    quantity: null,
    cost_buy: 95,
    cost_sell: 36,
    pricing_kind: 'consumable',
    sort_order: 40,
    worlds: null,
  },
  {
    source_key: 'pack_laser_cell',
    name: 'Laser Cell Rack',
    description: '40 charged capacitor cells, racked. Ship ordnance, cut and wound in this yard.',
    category: 'weapons',
    game_action: 'ammo_pack_laser',
    action_config: { effect: 'grant_ammo', ammo_item: 'laser_cell', amount: 40 },
    quantity: null,
    cost_buy: 160,
    cost_sell: 64,
    pricing_kind: 'ammo',
    sort_order: 50,
    worlds: ['dock'],
  },
  {
    source_key: 'part_hull_plate',
    name: 'Hull Plate',
    description: 'One cut and drilled section plate, stamped with its frame number. The unit the yard counts in.',
    category: 'ships',
    game_action: 'ship_part',
    action_config: { effect: 'grant_item', item_id: 'hull_plate', amount: 1 },
    quantity: null,
    cost_buy: 85,
    cost_sell: 34,
    pricing_kind: 'fixed',
    sort_order: 52,
    worlds: ['dock'],
  },
  {
    source_key: 'part_thruster_coil',
    name: 'Thruster Coil',
    description: 'A wound field coil out of a courier drive. The one fitting-out part nobody in this yard leaves lying about.',
    category: 'ships',
    game_action: 'ship_part',
    action_config: { effect: 'grant_item', item_id: 'thruster_coil', amount: 1 },
    quantity: null,
    cost_buy: 195,
    cost_sell: 78,
    pricing_kind: 'fixed',
    sort_order: 54,
    worlds: ['dock'],
  },
  {
    source_key: 'pack_nav_chart',
    name: 'Navigation Chart',
    description: 'A rolled survey chart of one district, drawn from a height somebody else climbed to. Marks that ground on your map; it does not put you on it.',
    category: 'tools',
    game_action: 'nav_chart',
    action_config: { effect: 'grant_item', item_id: 'nav_chart', amount: 1 },
    quantity: null,
    cost_buy: 220,
    cost_sell: 88,
    pricing_kind: 'consumable',
    sort_order: 56,
    worlds: ['citadel', 'dock'],
  },
  {
    source_key: 'ore_lodestone',
    name: 'Ferro-Basalt Lodestone',
    description: 'A belt-clipped slab of magnetite basalt off Cinder, trimmed and cased in the yard. Pulls loose salvage to you for twenty seconds, then the field bleeds off.',
    category: 'tools',
    game_action: 'refined_ore',
    action_config: { effect: 'grant_item', item_id: 'ferrobasalt', amount: 1 },
    quantity: null,
    cost_buy: 175,
    cost_sell: 70,
    pricing_kind: 'fixed',
    sort_order: 58,
    worlds: ['dock'],
  },
  {
    source_key: 'spell_stasis_5s',
    name: 'Stasis Rune',
    description: 'Spell consumable that pauses nearby NPC movement for 5 seconds.',
    category: 'spells',
    game_action: 'npc_pause_5s',
    action_config: { effect: 'pause_npcs', seconds: 5, radius: 24 },
    quantity: null,
    cost_buy: 125,
    cost_sell: 55,
    pricing_kind: 'consumable',
    sort_order: 60,
    worlds: null,
  },
  {
    source_key: 'spell_stasis_10s',
    name: 'Chrono Snare',
    description: 'Spell consumable that pauses nearby NPC movement for 10 seconds.',
    category: 'spells',
    game_action: 'npc_pause_10s',
    action_config: { effect: 'pause_npcs', seconds: 10, radius: 26 },
    quantity: null,
    cost_buy: 190,
    cost_sell: 84,
    pricing_kind: 'consumable',
    sort_order: 70,
    worlds: null,
  },
  {
    source_key: 'spell_stasis_30s',
    name: 'Time Lock Prism',
    description: 'Spell consumable that pauses nearby NPC movement for 30 seconds.',
    category: 'spells',
    game_action: 'npc_pause_30s',
    action_config: { effect: 'pause_npcs', seconds: 30, radius: 28 },
    quantity: null,
    cost_buy: 360,
    cost_sell: 160,
    pricing_kind: 'consumable',
    sort_order: 80,
    worlds: null,
  },
  {
    source_key: 'spell_stasis_60s',
    name: 'Temporal Vault Sigil',
    description: 'Spell consumable that pauses nearby NPC movement for 60 seconds.',
    category: 'spells',
    game_action: 'npc_pause_60s',
    action_config: { effect: 'pause_npcs', seconds: 60, radius: 30 },
    quantity: null,
    cost_buy: 620,
    cost_sell: 275,
    pricing_kind: 'consumable',
    sort_order: 90,
    worlds: null,
  },
  {
    source_key: 'spell_velocity_25',
    name: 'Fleetstep Spark',
    description: 'Spell consumable that boosts movement speed by 25% for 30 seconds.',
    category: 'spells',
    game_action: 'speed_boost_25',
    action_config: { effect: 'modify_speed', percent: 25, seconds: 30 },
    quantity: null,
    cost_buy: 135,
    cost_sell: 60,
    pricing_kind: 'consumable',
    sort_order: 100,
    worlds: null,
  },
  {
    source_key: 'spell_velocity_50',
    name: 'Rushline Glyph',
    description: 'Spell consumable that boosts movement speed by 50% for 30 seconds.',
    category: 'spells',
    game_action: 'speed_boost_50',
    action_config: { effect: 'modify_speed', percent: 50, seconds: 30 },
    quantity: null,
    cost_buy: 195,
    cost_sell: 86,
    pricing_kind: 'consumable',
    sort_order: 110,
    worlds: null,
  },
  {
    source_key: 'spell_velocity_75',
    name: 'Mach Surge Sigil',
    description: 'Spell consumable that boosts movement speed by 75% for 30 seconds.',
    category: 'spells',
    game_action: 'speed_boost_75',
    action_config: { effect: 'modify_speed', percent: 75, seconds: 30 },
    quantity: null,
    cost_buy: 280,
    cost_sell: 124,
    pricing_kind: 'consumable',
    sort_order: 120,
    worlds: null,
  },
  {
    source_key: 'spell_velocity_100',
    name: 'Velocity Crown',
    description: 'Spell consumable that doubles movement speed for 30 seconds.',
    category: 'spells',
    game_action: 'speed_boost_100',
    action_config: { effect: 'modify_speed', percent: 100, seconds: 30 },
    quantity: null,
    cost_buy: 410,
    cost_sell: 184,
    pricing_kind: 'consumable',
    sort_order: 130,
    worlds: null,
  },
  {
    source_key: 'spell_loot_grab_30',
    name: 'Vacuum Rune',
    description: 'Spell consumable that pulls nearby loot toward you for 30 seconds.',
    category: 'spells',
    game_action: 'loot_magnet_30s',
    action_config: { effect: 'loot_magnet', seconds: 30, radius: 30 },
    quantity: null,
    cost_buy: 165,
    cost_sell: 72,
    pricing_kind: 'consumable',
    sort_order: 140,
    worlds: null,
  },
  {
    source_key: 'spell_portal_ping_30',
    name: 'Gatefinder Echo',
    description: 'Spell consumable that highlights the nearest portal for 30 seconds.',
    category: 'spells',
    game_action: 'portal_ping_30s',
    action_config: { effect: 'portal_ping', seconds: 30 },
    quantity: null,
    cost_buy: 155,
    cost_sell: 68,
    pricing_kind: 'consumable',
    sort_order: 150,
    worlds: null,
  },
  {
    source_key: 'shield_5s',
    name: 'Aegis Shard',
    description: 'Spell consumable that raises a damage shield for 5 seconds.',
    category: 'spells',
    game_action: 'shield_5s',
    action_config: { effect: 'shield', seconds: 5 },
    quantity: null,
    cost_buy: 210,
    cost_sell: 92,
    pricing_kind: 'consumable',
    sort_order: 160,
    worlds: null,
  },
  {
    source_key: 'firepower_boost_25',
    name: 'Firepower Sigil',
    description: 'Weapon consumable that boosts weapon damage by 25% for 30 seconds.',
    category: 'weapons',
    game_action: 'firepower_boost_25',
    action_config: { effect: 'modify_firepower', percent: 25, seconds: 30 },
    quantity: null,
    cost_buy: 150,
    cost_sell: 66,
    pricing_kind: 'consumable',
    sort_order: 170,
    worlds: null,
  },
  {
    source_key: 'firepower_boost_50',
    name: 'Firepower Talisman',
    description: 'Weapon consumable that boosts weapon damage by 50% for 30 seconds.',
    category: 'weapons',
    game_action: 'firepower_boost_50',
    action_config: { effect: 'modify_firepower', percent: 50, seconds: 30 },
    quantity: null,
    cost_buy: 215,
    cost_sell: 95,
    pricing_kind: 'consumable',
    sort_order: 171,
    worlds: null,
  },
  {
    source_key: 'firepower_boost_75',
    name: 'Firepower Seal',
    description: 'Weapon consumable that boosts weapon damage by 75% for 30 seconds.',
    category: 'weapons',
    game_action: 'firepower_boost_75',
    action_config: { effect: 'modify_firepower', percent: 75, seconds: 30 },
    quantity: null,
    cost_buy: 305,
    cost_sell: 134,
    pricing_kind: 'consumable',
    sort_order: 172,
    worlds: null,
  },
  {
    source_key: 'firepower_boost_100',
    name: 'Firepower Crown',
    description: 'Weapon consumable that doubles weapon damage for 30 seconds.',
    category: 'weapons',
    game_action: 'firepower_boost_100',
    action_config: { effect: 'modify_firepower', percent: 100, seconds: 30 },
    quantity: null,
    cost_buy: 445,
    cost_sell: 196,
    pricing_kind: 'consumable',
    sort_order: 173,
    worlds: null,
  },
  /* The three bag expansion rigs. Bundled like every other hand-authored row,
   * and for a sharper reason than most: the one purchase a player makes to stop
   * their bag overflowing must not be the purchase that is missing when the API
   * is down and the bag is overflowing. `marketplace-offline.test.mjs` compares
   * every field below against the TypeScript. */
  {
    source_key: 'bag_expand_5',
    name: 'Stowage Webbing',
    description: 'A coil of load-bearing webbing and five clip points, lashed across the back of a pack. Hold it in your bag to fit it: +5 bag slots, permanently. No bag holds more than 60.',
    category: 'tools',
    game_action: 'bag_expand',
    action_config: { effect: 'grant_item', item_id: 'bag_expand_5', amount: 1 },
    quantity: null,
    cost_buy: 480,
    cost_sell: 192,
    pricing_kind: 'fixed',
    sort_order: 180,
    worlds: null,
  },
  {
    source_key: 'bag_expand_10',
    name: 'Expedition Harness',
    description: 'A frame harness with side panniers, cut for a long walk away from a counter. Hold it in your bag to fit it: +10 bag slots, permanently. No bag holds more than 60.',
    category: 'tools',
    game_action: 'bag_expand',
    action_config: { effect: 'grant_item', item_id: 'bag_expand_10', amount: 1 },
    quantity: null,
    cost_buy: 1150,
    cost_sell: 460,
    pricing_kind: 'fixed',
    sort_order: 181,
    worlds: null,
  },
  {
    source_key: 'bag_expand_15',
    name: 'Quartermaster Rig',
    description: "The rig a supply officer wears to carry a squad's worth of everything at once. Hold it in your bag to fit it: +15 bag slots, permanently. No bag holds more than 60.",
    category: 'tools',
    game_action: 'bag_expand',
    action_config: { effect: 'grant_item', item_id: 'bag_expand_15', amount: 1 },
    quantity: null,
    cost_buy: 2100,
    cost_sell: 840,
    pricing_kind: 'fixed',
    sort_order: 182,
    worlds: null,
  },
  {
    source_key: 'cosmetic_headgear_aurora',
    name: 'Aurora Racer Skin',
    description: 'Limited-edition character colourway — glacier teal with a cyan pulse. Equip in the F2 Character menu.',
    category: 'cosmetic',
    game_action: 'cosmetic_char_skin',
    action_config: { effect: 'unlock_cosmetic', kind: 'character', cosmetic_id: 'char_aurora' },
    quantity: null,
    cost_buy: 240,
    cost_sell: 96,
    pricing_kind: 'fixed',
    sort_order: 200,
    worlds: null,
  },
  {
    source_key: 'cosmetic_shirt_trail',
    name: 'Midnight Ops Skin',
    description: 'Limited-edition character colourway — blacked-out kit with cold blue trim. Equip in the F2 Character menu.',
    category: 'cosmetic',
    game_action: 'cosmetic_char_skin',
    action_config: { effect: 'unlock_cosmetic', kind: 'character', cosmetic_id: 'char_midnight' },
    quantity: null,
    cost_buy: 260,
    cost_sell: 104,
    pricing_kind: 'fixed',
    sort_order: 210,
    worlds: null,
  },
  {
    source_key: 'cosmetic_pants_glide',
    name: 'Ember Vanguard Skin',
    description: 'Limited-edition character colourway — scorched charcoal and molten orange. Equip in the F2 Character menu.',
    category: 'cosmetic',
    game_action: 'cosmetic_char_skin',
    action_config: { effect: 'unlock_cosmetic', kind: 'character', cosmetic_id: 'char_ember' },
    quantity: null,
    cost_buy: 280,
    cost_sell: 112,
    pricing_kind: 'fixed',
    sort_order: 220,
    worlds: null,
  },
  {
    source_key: 'cosmetic_skin_jade',
    name: 'Jade Sovereign Skin',
    description: 'Limited-edition character colourway — deep jade with a gold edge. Equip in the F2 Character menu.',
    category: 'cosmetic',
    game_action: 'cosmetic_char_skin',
    action_config: { effect: 'unlock_cosmetic', kind: 'character', cosmetic_id: 'char_jade' },
    quantity: null,
    cost_buy: 320,
    cost_sell: 128,
    pricing_kind: 'fixed',
    sort_order: 230,
    worlds: null,
  },
  {
    source_key: 'cosmetic_skin_violet',
    name: 'Violet Mirage Skin',
    description: 'Limited-edition character colourway — twilight violet with a magenta spark. Equip in the F2 Character menu.',
    category: 'cosmetic',
    game_action: 'cosmetic_char_skin',
    action_config: { effect: 'unlock_cosmetic', kind: 'character', cosmetic_id: 'char_violet' },
    quantity: null,
    cost_buy: 360,
    cost_sell: 144,
    pricing_kind: 'fixed',
    sort_order: 240,
    worlds: null,
  },
  {
    source_key: 'cosmetic_car_neon',
    name: 'Neon Circuit Livery',
    description: 'Limited-edition car livery — magenta body with cyan rims. Apply from Esc → Customise mount while driving; one use, then yours to keep.',
    category: 'mounts',
    game_action: 'cosmetic_vehicle_skin',
    action_config: { effect: 'grant_item', item_id: 'skin_car_neon' },
    quantity: null,
    cost_buy: 420,
    cost_sell: 168,
    pricing_kind: 'fixed',
    sort_order: 400,
    worlds: null,
  },
  {
    source_key: 'cosmetic_car_inferno',
    name: 'Inferno Livery',
    description: 'Limited-edition car livery — race red with gold alloys. Apply from Esc → Customise mount while driving; one use, then yours to keep.',
    category: 'mounts',
    game_action: 'cosmetic_vehicle_skin',
    action_config: { effect: 'grant_item', item_id: 'skin_car_inferno' },
    quantity: null,
    cost_buy: 460,
    cost_sell: 184,
    pricing_kind: 'fixed',
    sort_order: 410,
    worlds: null,
  },
  {
    source_key: 'cosmetic_car_phantom',
    name: 'Phantom Livery',
    description: 'Limited-edition car livery — stealth black with chalk-white wheels. Apply from Esc → Customise mount while driving; one use, then yours to keep.',
    category: 'mounts',
    game_action: 'cosmetic_vehicle_skin',
    action_config: { effect: 'grant_item', item_id: 'skin_car_phantom' },
    quantity: null,
    cost_buy: 500,
    cost_sell: 200,
    pricing_kind: 'fixed',
    sort_order: 420,
    worlds: null,
  },
  {
    source_key: 'cosmetic_car_toxic',
    name: 'Toxic Surge Livery',
    description: 'Limited-edition car livery — venom green over black rims. Apply from Esc → Customise mount while driving; one use, then yours to keep.',
    category: 'mounts',
    game_action: 'cosmetic_vehicle_skin',
    action_config: { effect: 'grant_item', item_id: 'skin_car_toxic' },
    quantity: null,
    cost_buy: 540,
    cost_sell: 216,
    pricing_kind: 'fixed',
    sort_order: 430,
    worlds: null,
  },
  {
    source_key: 'cosmetic_car_azure',
    name: 'Azure Bolt Livery',
    description: 'Limited-edition car livery — electric blue with silver alloys. Apply from Esc → Customise mount while driving; one use, then yours to keep.',
    category: 'mounts',
    game_action: 'cosmetic_vehicle_skin',
    action_config: { effect: 'grant_item', item_id: 'skin_car_azure' },
    quantity: null,
    cost_buy: 600,
    cost_sell: 240,
    pricing_kind: 'fixed',
    sort_order: 440,
    worlds: null,
  },
  {
    source_key: 'mount_strength_1',
    name: 'Mount Strength I',
    description: 'Car upgrade: sharper acceleration off the line. Permanent, stacks with higher tiers.',
    category: 'mounts',
    game_action: 'mount_strength_1',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'strength', tier: 1 },
    quantity: null,
    cost_buy: 260,
    cost_sell: 104,
    pricing_kind: 'fixed',
    sort_order: 300,
    worlds: null,
  },
  {
    source_key: 'mount_strength_2',
    name: 'Mount Strength II',
    description: 'Car upgrade: even sharper acceleration. Permanent, replaces tier I.',
    category: 'mounts',
    game_action: 'mount_strength_2',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'strength', tier: 2 },
    quantity: null,
    cost_buy: 460,
    cost_sell: 184,
    pricing_kind: 'fixed',
    sort_order: 301,
    worlds: null,
  },
  {
    source_key: 'mount_strength_3',
    name: 'Mount Strength III',
    description: 'Car upgrade: maximum acceleration. Permanent, replaces tier II.',
    category: 'mounts',
    game_action: 'mount_strength_3',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'strength', tier: 3 },
    quantity: null,
    cost_buy: 720,
    cost_sell: 288,
    pricing_kind: 'fixed',
    sort_order: 302,
    worlds: null,
  },
  {
    source_key: 'mount_shield_1',
    name: 'Mount Shield I',
    description: 'Car upgrade: reinforced chassis softens impacts. Permanent, stacks with higher tiers.',
    category: 'mounts',
    game_action: 'mount_shield_1',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'shield', tier: 1 },
    quantity: null,
    cost_buy: 280,
    cost_sell: 112,
    pricing_kind: 'fixed',
    sort_order: 310,
    worlds: null,
  },
  {
    source_key: 'mount_shield_2',
    name: 'Mount Shield II',
    description: 'Car upgrade: heavier plating. Permanent, replaces tier I.',
    category: 'mounts',
    game_action: 'mount_shield_2',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'shield', tier: 2 },
    quantity: null,
    cost_buy: 500,
    cost_sell: 200,
    pricing_kind: 'fixed',
    sort_order: 311,
    worlds: null,
  },
  {
    source_key: 'mount_shield_3',
    name: 'Mount Shield III',
    description: 'Car upgrade: maximum protection. Permanent, replaces tier II.',
    category: 'mounts',
    game_action: 'mount_shield_3',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'shield', tier: 3 },
    quantity: null,
    cost_buy: 780,
    cost_sell: 312,
    pricing_kind: 'fixed',
    sort_order: 312,
    worlds: null,
  },
  {
    source_key: 'mount_power_1',
    name: 'Mount Power I',
    description: 'Car upgrade: higher top speed. Permanent, stacks with higher tiers.',
    category: 'mounts',
    game_action: 'mount_power_1',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'power', tier: 1 },
    quantity: null,
    cost_buy: 300,
    cost_sell: 120,
    pricing_kind: 'fixed',
    sort_order: 320,
    worlds: null,
  },
  {
    source_key: 'mount_power_2',
    name: 'Mount Power II',
    description: 'Car upgrade: even higher top speed. Permanent, replaces tier I.',
    category: 'mounts',
    game_action: 'mount_power_2',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'power', tier: 2 },
    quantity: null,
    cost_buy: 520,
    cost_sell: 208,
    pricing_kind: 'fixed',
    sort_order: 321,
    worlds: null,
  },
  {
    source_key: 'mount_power_3',
    name: 'Mount Power III',
    description: 'Car upgrade: maximum top speed. Permanent, replaces tier II.',
    category: 'mounts',
    game_action: 'mount_power_3',
    action_config: { effect: 'grant_mount_power', mount: 'car', power: 'power', tier: 3 },
    quantity: null,
    cost_buy: 820,
    cost_sell: 328,
    pricing_kind: 'fixed',
    sort_order: 322,
    worlds: null,
  },].map(Object.freeze));

/**
 * The catalogue a vendor in `worldId` would be served, priced for that world.
 *
 * @param {string|null} worldId
 * @returns {Array<object>} rows in the same shape `/api/marketplace/items`
 *   returns: `id`, `source_key`, `name`, `description`, `category`, `image`,
 *   `game_action`, `action_config`, `quantity`, `cost_buy`, `cost_sell`,
 *   `sort_order`. `image` is the empty string - `MarketplaceUI._renderMktArt`
 *   already draws a styled SVG placeholder for a row with no art, which is the
 *   right answer when the art service is the thing that is down.
 */
export function offlineCatalog(worldId) {
  const market = WORLD_MARKETS[worldId] ?? null;
  if (!market) return [];
  const out = [];
  for (const item of OFFLINE_BASE_ITEMS) {
    if (item.worlds && !item.worlds.includes(worldId)) continue;
    let buyMul = 1;
    let sellMul = 1;
    if (item.pricing_kind === 'ammo') {
      buyMul = market.buy.ammo;
      sellMul = market.sell.ammo;
    } else if (item.pricing_kind === 'consumable') {
      buyMul = market.buy.consumable;
      sellMul = market.sell.consumable;
    }
    out.push({
      /* `id` is what `buy()` looks a row up by and what the trade receipt
       * carries. `source_key:world` is exactly the key the seeder writes, so
       * an offline purchase and an online one name the same row - which
       * matters the moment the API comes back up mid-session. */
      id: `${item.source_key}:${worldId}`,
      source_key: item.source_key,
      name: item.name,
      description: item.description,
      category: item.category,
      image: '',
      game_action: item.game_action,
      action_config: item.action_config,
      quantity: item.quantity,
      cost_buy: Math.max(1, Math.round(item.cost_buy * buyMul)),
      cost_sell: Math.max(1, Math.round(item.cost_sell * sellMul)),
      sort_order: item.sort_order,
      /** Marks a row the API did not serve. The UI says so once, at the top. */
      offline: true,
    });
  }
  out.sort((a, b) => a.sort_order - b.sort_order);
  return out;
}
